name: open_veterinarian
description: "The ultimate open-source assistance app for Veterinarians."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.1.1
  file_picker: ^8.1.3
  supabase_flutter: ^2.6.0
  flutter_svg: ^2.0.10+1
  video_player: ^2.9.1
  chewie: 1.8.5
  flutter_tts: 4.0.2
  speech_to_text: 6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#0A0A1A"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
