import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class ReportService {
  static Future<void> generateClientSummary({
    required String petName,
    required String species,
    required double weight,
    required String reasonForVisit,
    required Map<String, String> findings, // e.g., {'Heart Rate': '120 bpm'}
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildHeader(petName, species),
              pw.SizedBox(height: 20),
              _buildSectionTitle('Patient Information'),
              _buildInfoRow('Name', petName),
              _buildInfoRow('Species', species),
              _buildInfoRow('Weight', '$weight kg'),
              pw.SizedBox(height: 20),
              _buildSectionTitle('Reason for Visit'),
              pw.Text(reasonForVisit, style: pw.TextStyle(fontSize: 12)),
              pw.SizedBox(height: 20),
              _buildSectionTitle('Clinical Findings'),
              ...findings.entries.map((e) => _buildInfoRow(e.key, e.value)).toList(),
              pw.Spacer(),
              pw.Divider(color: PdfColors.cyan),
              pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text(
                  'Generated by Open Veterinarian',
                  style: pw.TextStyle(fontSize: 10, color: PdfColors.grey),
                ),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  static pw.Widget _buildHeader(String petName, String species) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: const pw.BoxDecoration(color: PdfColors.cyan),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Clinical Summary',
            style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
          ),
          pw.Text(
            'Patient: $petName ($species)',
            style: const pw.TextStyle(fontSize: 14, color: PdfColors.white),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSectionTitle(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 8),
      child: pw.Text(
        title.toUpperCase(),
        style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.cyan),
      ),
    );
  }

  static pw.Widget _buildInfoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 12)),
          pw.Text(value, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }
}
